name: Docker Build and Publish

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: 
      - trunk
    tags:
      - 'v*.*.*'
  pull_request_target:
    branches: 
      - trunk

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ${{ github.repository_owner }}/simple-docker
  # TODO: Set registry. Use docker.io for DockerHub
  REGISTRY: ghcr.io
  DOCKERFILE_PATH: Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./simple-docker/metadata@trunk
        id: metadata
        with:
          image-name: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ steps.metadata.outputs.file }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
